=== osawa-koki/cpu-usage-watcher.cs/src/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="config">
  <xsd:complexType>
    <xsd:sequence>

      <xsd:element name="cpu_usage_threshold_percent" type="xsd:nonNegativeInteger" />
      <xsd:element name="cpu_observing_interval_millisecond" type="xsd:nonNegativeInteger" />
      <xsd:element name="idle_time_millisecond" type="xsd:nonNegativeInteger" />

      <xsd:element name="targets">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="target" minOccurs="0"  maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="value" type="xsd:string" />
                  <xsd:element name="algo">
                    <xsd:simpleType>
                      <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="MD5" />
                        <xsd:enumeration value="SHA1" />
                        <xsd:enumeration value="SHA256" />
                        <xsd:enumeration value="SHA384" />
                        <xsd:enumeration value="SHA512" />
                      </xsd:restriction>
                    </xsd:simpleType>
                  </xsd:element>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== osawa-koki/cpu-usage-watcher.cs/src/config.xml
<?xml version="1.0" encoding="utf-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

  <cpu_usage_threshold_percent>50</cpu_usage_threshold_percent>
  <cpu_observing_interval_millisecond>5</cpu_observing_interval_millisecond>
  <idle_time_millisecond>300</idle_time_millisecond>

  <targets>
    <target>
      <value>http://www.google.com</value>
      <algo>MD5</algo>
    </target>
    <target>
      <value>http://www.yahoo.com</value>
      <algo>SHA1</algo>
    </target>
    <target>
      <value>http://www.bing.com</value>
      <algo>SHA256</algo>
    </target>
    <target>
      <value>http://www.ask.com</value>
      <algo>SHA512</algo>
    </target>
  </targets>

  </config>
